import Link from "next/link";

import { ConceptMap } from "@/components/concept-map";
import { Badge } from "@/components/ui/badge";

export default function HomePage() {
  return (
    <div className="space-y-8">
      <section className="relative overflow-hidden rounded-3xl border border-marino/20 bg-white p-7 shadow-card md:p-10">
        <div className="absolute -right-20 -top-16 h-56 w-56 rounded-full bg-arena/60 blur-2xl" />
        <div className="absolute -bottom-16 left-8 h-40 w-40 rounded-full bg-musgo/20 blur-2xl" />

        <div className="relative space-y-5">
          <Badge tone="accent">Collaborative platform</Badge>
          <h1 className="max-w-4xl font-serif text-4xl leading-tight text-tinta md:text-5xl">
            A collaborative literature review on Administrative Burden and Citizen Experience
          </h1>
          <p className="max-w-3xl text-lg text-marino/85">
            An academic space for mapping empirical and theoretical work on Administrative Burden
            in the tradition of Herd and Moynihan, with a focus on how citizens experience the
            state.
          </p>

          <div className="flex flex-wrap gap-3">
            <Link
              href="/library"
              className="rounded-full bg-marino px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-tinta"
            >
              Explore the literature
            </Link>
            <Link
              href="/submit"
              className="rounded-full border border-marino/30 bg-white px-5 py-2.5 text-sm font-semibold text-marino transition hover:bg-fondo"
            >
              Submit an article
            </Link>
          </div>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        <InfoCard
          title="What this platform is"
          text="A collaborative review that combines thematic exploration, article submission, and a mock editorial workflow for discussing new evidence."
        />
        <InfoCard
          title="What you can do"
          text="Filter the literature by burden type, analytical relationship, Citizen Experience stage, country, method, and publication status."
        />
        <InfoCard
          title="How it will evolve"
          text="The architecture is already prepared for future Supabase integration, ORCID login, and real double-approval editorial logic."
        />
      </section>

      <section className="space-y-5 px-1">
        <div className="max-w-4xl space-y-3">
          <h2 className="font-serif text-2xl text-tinta md:text-[30px]">
            Understanding Administrative Burden
          </h2>
          <p className="text-sm leading-6 text-marino/82 md:text-[15px]">
            Administrative burden refers to the costs citizens experience when they learn about,
            comply with, and psychologically process interactions with the state. In the Herd and
            Moynihan tradition, these costs are produced through policy design and implementation,
            shaping who can access public programs and under what conditions.
          </p>
        </div>

        <div className="grid gap-3 md:grid-cols-3">
          <ConceptCard
            title="Learning Costs"
            text="The effort required to discover programs, interpret rules, and understand eligibility, rights, and procedures."
          />
          <ConceptCard
            title="Compliance Costs"
            text="The time and administrative work needed to provide information, complete procedures, and satisfy program requirements."
          />
          <ConceptCard
            title="Psychological Costs"
            text="The stress, stigma, loss of autonomy, and uncertainty generated by administrative encounters and oversight."
          />
        </div>
      </section>

      <ConceptMap />
    </div>
  );
}

function InfoCard({ title, text }: { title: string; text: string }) {
  return (
    <article className="rounded-2xl border border-marino/20 bg-white p-5 shadow-card">
      <h2 className="font-serif text-xl text-tinta">{title}</h2>
      <p className="mt-2 text-sm text-marino/80">{text}</p>
    </article>
  );
}

function ConceptCard({ title, text }: { title: string; text: string }) {
  return (
    <article className="rounded-[20px] bg-white/72 px-5 py-4 shadow-[0_8px_24px_rgba(16,36,63,0.04)] ring-1 ring-marino/8">
      <h3 className="font-serif text-xl text-tinta">{title}</h3>
      <p className="mt-2 text-sm leading-6 text-marino/78">{text}</p>
    </article>
  );
}
